services:
  - type: web
    name: backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma db push --accept-data-loss
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
